### PR TITLE
Fix source of truth for country names across app

### LINKED ISSUE #167: Use country full name instead of alpha codes
* Using alpha codes is unsustainable with OSM
* Also need to change users_clock function to avoid double-counting country edits

### PR DESCRIPTION
**Pull request by kamicut**
- Closes #167 by moving to a single source of truth with natural earth countries.geojson from https://github.com/azavea/osmesa/blob/master/src/analytics/src/main/resources/countries.geojson

- Takes a stab at #173 by generating new user data

### CODE REVIEW

File: api/src/models/userCountryEdits.js [hunk 1]
```diff
@@ -1,9 +1,4 @@
 const db = require('../db/connection')
-const util = require('util')
```
Comment (scisco) [inline api/src/models/userCountryEdits.js]: This is needed in the clocks file for users. It either has to be added to user clocks or be restored here.

File: api/src/users_clock.js [hunk 2]
```diff
@@ -43,9 +43,6 @@ async function updateCountries (userID, countryEditList) {
   // get total edits for a given user
   countryEditList.forEach((tuple) => {
     let countryName = tuple.name
-    if (isState(countryName)) {
```
Comment (scisco) [inline api/src/users_clock.js]: This is essential for marking all US states under the US name
