### PR TITLE
Fix/design issues

### LINKED ISSUE #364: Users page uses "you" in teams section
image

On the User page, "you" should be the user's display name.

### PR DESCRIPTION
**Pull request by LanesGood**
Multiple minor design fixes to address:
- Country map alignment
image

- Dashboard sidebar message
image

- App height
image

- Inclusion of loading state in other pages, and full height headers:
image

- Table scroll bars:
image

Closes #364 and contributes to #382

### CODE REVIEW

File: components/dashboard/DashboardSidebar.js [hunk 1]
```diff
@@ -12,7 +12,8 @@ function formatCountryList (userCountries) {
 }
 
 function DashboardSidebar (props) {
-  const { teams, osmesaData } = props
+  const { teams, osmesaData, loggedIn } = props
+  console.log(props)
```
Comment (kamicut) [inline components/dashboard/DashboardSidebar.js]:
```suggestion
```
