### PR TITLE
fix frontpage stats and graphs

### LINKED ISSUE #79: Users charts are missing on the front page
It only shows them as loading
screenshot 2018-11-28 13 46 02

### LINKED ISSUE #81: frontpage stats are broken
screenshot 2018-11-28 13 52 39

### PR DESCRIPTION
**Pull request by sethvincent**
closes #79 
closes #81 

screen shot 2018-11-28 at 12 49 45 pm
screen shot 2018-11-28 at 12 50 11 pm

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -31,7 +23,8 @@ export class Home extends Component {
     const { topStats, project: projectName } = this.props
     if (!topStats) return <div />
 
-    const { campaign_total, records, num_users, features, top_edits, edits_by_country } = topStats
+    console.log('topStats', topStats)
```
Comment (kamicut) [inline pages/index.js]: Remove this console.log

Comment (kamicut) [inline pages/index.js]:
```suggestion
```
